name: transferase utilities integrations tests

# Should run in the middle of the night (Pacific time)
on:
  schedule:
    - cron: "* 12 * * *"
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    container: andrewdavidsmith/transferase-test-data-small
    steps:
      - name: Build transferase
        run: |
          cd /tmp
          git clone https://github.com/andrewdavidsmith/transferase.git
          cd transferase
          cmake -B build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j4
          cmake --install build --prefix=/usr
          ls -lR /usr/bin
      - name: Run the integration test script
        run: |
          ls -lR /usr/bin
          cd /data && && ./workflow.sh .
