name: transferase utilities integrations tests

# Should run in the middle of the night (Pacific time)
on:
  schedule:
    - cron: "* 12 * * *"
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    container: andrewdavidsmith/transferase-test-data-small
    steps:
      - name: Run the integration test script
        run: |
          cd /data && cat sha256sum.txt
          # ./workflow.sh .
