name: Run integration tests for transferase

on:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    container: andrewdavidsmith/transferase-test-data-small
    steps:
      - uses: actions/checkout@v4
      - name: Build transferase
        run: |
          ls -ltrh /data/
